name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.7"
            psycopg: "psycopg2"
          - python: "3.8"
            psycopg: "psycopg3"
          - python: "3.9"
            psycopg: "psycopg2"
          - python: "3.10"
            psycopg: "psycopg3"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Add fr_FR ISO-8859-1 for test purposes
        run: |
           sudo locale-gen fr_FR
           sudo update-locale
      - name: Test
        run: tox -e py-${{ matrix.psycopg }}
